# Generated by Django 5.1.6 on 2025-02-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='survey_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='analysis_cluster',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('CoreNet Event', 'CoreNet Event'), ('Event & Conference', 'Event & Conference'), ('HomeOffice', 'HomeOffice')], default='Standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='analysis_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='city_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='end_survey_titles',
            field=models.JSONField(blank=True, default=list, help_text='List of titles to show at the end of survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='expired_survey_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='expired_survey_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_participants',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='short_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='street_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='token',
            field=models.CharField(blank=True, help_text='Only lowercase letters, no special characters, no spaces', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', max_length=2),
        ),
    ]
