# Generated by Django 5.1.6 on 2025-02-25 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_text_question_question_question_headline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey_text',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='expired_survey_text',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='expired_survey_title',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='language',
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', help_text='Primary language of this question', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, help_text='Placeholder text for each language', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.JSONField(default=dict, help_text="Question text for each language: {'en': 'English question', 'de': 'German question'}"),
        ),
        migrations.AddField(
            model_name='response',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', help_text='Language used for this response', max_length=2),
        ),
        migrations.AddField(
            model_name='survey',
            name='expired_survey_texts',
            field=models.JSONField(blank=True, default=dict, help_text='Expired survey texts for each language'),
        ),
        migrations.AddField(
            model_name='survey',
            name='expired_survey_titles',
            field=models.JSONField(blank=True, default=dict, help_text='Expired survey titles for each language'),
        ),
        migrations.AddField(
            model_name='survey',
            name='headlines',
            field=models.JSONField(blank=True, default=dict, help_text="Headline text for each language: {'en': 'English Headline', 'de': 'German Headline'}"),
        ),
        migrations.AddField(
            model_name='survey',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], max_length=2), default=['en'], help_text='List of languages supported by this survey', size=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_texts',
            field=models.JSONField(blank=True, default=dict, help_text='Survey introduction text for each language'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_survey_titles',
            field=models.JSONField(blank=True, default=dict, help_text='Titles to show at the end of survey for each language'),
        ),
    ]
