# Generated by Django 5.1.6 on 2025-02-25 10:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_question_headline_remove_question_survey_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], max_length=2), default=list, help_text='List of languages supported by this survey', size=None),
        ),
    ]
