# Generated by Django 5.1.6 on 2025-02-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_placeholder',
        ),
    ]
