# Generated by Django 5.1.6 on 2025-02-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_question_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_survey_texts',
            field=models.JSONField(blank=True, default=dict, help_text='Messages to show at the end of survey for each language'),
        ),
    ]
