# Generated by Django 5.1.6 on 2025-03-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_rename_end_date_survey_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Only lowercase letters, no special characters, no spaces', max_length=100, unique=True)),
                ('description', models.CharField(help_text="Description of the token's purpose (e.g., 'Group A', 'Office Staff')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='surveys.survey')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
