# Generated by Django 5.1.6 on 2025-03-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_migrate_existing_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='survey_token',
            field=models.ForeignKey(blank=True, help_text='Reference to the specific token used (if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='surveys.surveytoken'),
        ),
        migrations.AddField(
            model_name='response',
            name='token',
            field=models.CharField(blank=True, help_text='The token used to access this survey', max_length=100, null=True),
        ),
    ]
