# Generated by Django 5.1.6 on 2025-03-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_surveyanalysissummary_wordcluster_responseword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the custom cluster (e.g., 'Customer Service')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this cluster represents')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords/phrases that belong to this cluster')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cluster is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_clusters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Word Cluster',
                'verbose_name_plural': 'Custom Word Clusters',
                'ordering': ['name'],
            },
        ),
    ]
