# Generated by Django 5.1.6 on 2025-03-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_customwordcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='processed',
            field=models.BooleanField(default=False, help_text='Whether this answer has been processed for word extraction'),
        ),
        migrations.AddField(
            model_name='customwordcluster',
            name='last_processed',
            field=models.DateTimeField(blank=True, help_text='When this cluster was last processed', null=True),
        ),
        migrations.AddField(
            model_name='customwordcluster',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Number of words associated with this cluster'),
        ),
    ]
