# Generated by Django 5.1.6 on 2025-03-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_answer_processed_customwordcluster_last_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseword',
            name='custom_clusters',
            field=models.ManyToManyField(blank=True, related_name='words', to='surveys.customwordcluster'),
        ),
    ]
