# Generated by Django 5.1.6 on 2025-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_responseword_custom_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseword',
            name='assigned_cluster',
            field=models.CharField(blank=True, help_text='Directly assigned cluster name for this word', max_length=100, null=True),
        ),
    ]
