# Generated by Django 5.1.6 on 2025-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_responseword_assigned_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcluster',
            name='category',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=50),
        ),
        migrations.AlterField(
            model_name='wordcluster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordcluster',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordcluster',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wordcluster',
            name='is_neutral',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wordcluster',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wordcluster',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wordcluster',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
