# Generated by Django 5.1.6 on 2025-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_wordcluster_custom_cluster_id_wordcluster_nps_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='End date and time for the survey', null=True),
        ),
    ]
