# Generated by Django 5.1.6 on 2025-03-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_survey_start_datetime_alter_survey_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='analysis_end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='short_id',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='street_number',
        ),
    ]
