# Generated by Django 5.1.6 on 2025-03-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_remove_survey_analysis_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='start_survey_texts',
            field=models.JSONField(blank=True, default=dict, help_text='Messages to show when survey has not started yet for each language'),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_survey_titles',
            field=models.JSONField(blank=True, default=dict, help_text='Titles to show when survey has not started yet for each language'),
        ),
    ]
