# Generated by Django 5.1.6 on 2025-03-07 15:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_survey_start_survey_texts_survey_start_survey_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('headlines', models.JSONField(blank=True, default=dict, help_text="Headline text for each language: {'en': 'English Headline', 'de': 'German Headline'}")),
                ('survey_texts', models.JSONField(blank=True, default=dict, help_text='Survey introduction text for each language')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], max_length=2), default=list, help_text='List of languages supported by this template', size=None)),
                ('format', models.CharField(choices=[('online', 'Online'), ('face_to_face', 'Face to Face')], default='online', max_length=20)),
                ('type', models.CharField(choices=[('friends_family', 'Friends and Family'), ('public', 'Public'), ('professional', 'Professional'), ('single_company', 'Single Company'), ('intracompany', 'Intracompany')], default='public', max_length=20)),
                ('analysis_cluster', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('CoreNet Event', 'CoreNet Event'), ('Event & Conference', 'Event & Conference'), ('HomeOffice', 'HomeOffice')], default='Standard', max_length=50, null=True)),
                ('start_survey_titles', models.JSONField(blank=True, default=dict, help_text='Titles to show when survey has not started yet for each language')),
                ('start_survey_texts', models.JSONField(blank=True, default=dict, help_text='Messages to show when survey has not started yet for each language')),
                ('end_survey_titles', models.JSONField(blank=True, default=dict, help_text='Titles to show at the end of survey for each language')),
                ('end_survey_texts', models.JSONField(blank=True, default=dict, help_text='Messages to show at the end of survey for each language')),
                ('expired_survey_titles', models.JSONField(blank=True, default=dict, help_text='Expired survey titles for each language')),
                ('expired_survey_texts', models.JSONField(blank=True, default=dict, help_text='Expired survey texts for each language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clusters', models.ManyToManyField(blank=True, related_name='templates', to='surveys.customwordcluster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
