# Generated by Django 5.1.6 on 2025-03-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=dict, help_text="Question text for each language: {'en': 'English question', 'de': 'German question'}")),
                ('placeholders', models.JSONField(blank=True, default=dict, help_text='Placeholder text for each language', null=True)),
                ('type', models.CharField(choices=[('nps', 'Net Promoter Score'), ('free_text', 'Free Text')], max_length=20)),
                ('order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', help_text='Primary language of this question', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.template')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
