# Generated by Django 5.1.6 on 2025-03-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_templatequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this survey was created from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_surveys', to='surveys.template'),
        ),
    ]
