# Generated by Django 5.1.6 on 2025-03-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_remove_token_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='sentence_sentiments',
            field=models.JSONField(blank=True, default=list, help_text="List of sentences with sentiment scores: [{'text': 'Sentence text', 'sentiment': 0.5}, ...]"),
        ),
        migrations.AddField(
            model_name='responseword',
            name='sentence_index',
            field=models.IntegerField(blank=True, help_text='Index of the sentence this word was extracted from', null=True),
        ),
        migrations.AddField(
            model_name='responseword',
            name='sentence_text',
            field=models.TextField(blank=True, help_text='The sentence this word was extracted from', null=True),
        ),
    ]
