# Generated by Django 5.1.6 on 2025-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanalysissummary',
            name='metrics',
            field=models.JSONField(default=dict, help_text='Detailed metrics data for clusters and other analysis'),
        ),
    ]
