# Generated by Django 5.1.6 on 2025-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_surveyanalysissummary_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customwordcluster',
            name='descriptions',
            field=models.JSONField(blank=True, default=dict, help_text="Description for each language: {'en': 'English Description', 'de': 'German Description', 'fr': 'French Description', 'es': 'Spanish Description'}"),
        ),
        migrations.AddField(
            model_name='customwordcluster',
            name='multilingual_keywords',
            field=models.JSONField(blank=True, default=dict, help_text="Keywords for each language: {'en': ['word1', 'word2'], 'de': ['wort1', 'wort2'], 'fr': ['mot1', 'mot2'], 'es': ['palabra1', 'palabra2']}"),
        ),
        migrations.AddField(
            model_name='customwordcluster',
            name='names',
            field=models.JSONField(blank=True, default=dict, help_text="Name for each language: {'en': 'English Name', 'de': 'German Name', 'fr': 'French Name', 'es': 'Spanish Name'}"),
        ),
    ]
